# Generated by Django 4.0.1 on 2022-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['completed']},
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.URLField(default='', max_length=300),
        ),
    ]
