# Generated by Django 4.0.1 on 2022-01-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_member_alter_project_options_alter_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(related_name='projects', to='projects.Member'),
        ),
    ]
