# Generated by Django 4.0.1 on 2022-01-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_member_lastname_project_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(blank=True, to='projects.Member'),
        ),
    ]
